
    // Arrays com nomes fictícios
    var nomes = ["João", "Maria", "Pedro", "Ana", "Carlos", "Mariana", "André", "Laura", "Rafael", "Isabela", "Fernando", "Camila", "Gustavo", "Juliana", "Rodrigo", "Amanda", "Lucas", "Carolina", "Tiago", "Gabriela", "Eduardo", "Larissa", "Daniel", "Letícia", "Marcelo", "Beatriz", "Alexandre", "Vanessa", "Felipe", "Manuela", "Renato", "Helena", "Guilherme", "Natália", "Hugo", "Sophia", "Leonardo", "Júlia", "Vitor", "Luiza", "Thiago", "Débora", "Matheus", "Carla", "Bruno", "Renata", "Ricardo", "Tatiana", "Paulo", "Patrícia", "Diego", "Mariane", "Sérgio", "Sabrina", "Roberto", "Bianca", "Miguel", "Mara", "Cristiano", "Raquel", "Raul", "Valentina", "Alex", "Priscila", "Arthur", "Luana", "Nuno", "Susana", "Simão", "Teresa", "Fábio", "Inês", "Pedro", "Rita", "Daniel", "Sandra", "Luís", "Cátia", "André", "Marta", "Nelson", "Carina", "Hélder", "Andreia", "Ricardo", "Carmen", "Samuel", "Isabel", "Marco", "Carla", "Tiago", "Mónica", "José", "Catarina", "Manuel", "Lúcia", "António", "Filipa", "Joana", "Andreia", "Rui", "Sara", "Jaime", "Liliana", "Mário", "Jéssica", "Adriano", "Diana", "Diogo", "Margarida", "Jorge", "Telma", "Carlos", "Filipe", "Rafael", "Maria", "Rita", "Rogério", "Ana", "Augusto", "Patrícia", "Maurício", "Teresa", "Cláudio", "Andreia", "Alberto", "Sandra", "André", "Catarina", "Emanuel", "Susana", "Filipe", "Sílvia", "Tomás", "Célia", "Guilherme", "Rita", "Henrique", "Joana", "Francisco", "Mónica", "Leonardo", "Inês", "Santiago", "Bianca", "Joaquim", "Rafaela", "Luiz", "Lara", "Enzo", "Vitória", "Elias", "Lívia", "Lorenzo", "Valentina", "Emanuel", "Ana", "Carlos", "Mariana", "André", "Laura", "Rafael", "Isabela", "Fernando", "Camila", "Gustavo", "Juliana", "Rodrigo", "Amanda", "Lucas", "Carolina", "Tiago", "Gabriela"];
    var sobrenomes = ["Silva", "Santos", "Souza", "Oliveira", "Pereira", "Rodrigues", "Almeida", "Ferreira", "Lima", "Gomes", "Costa", "Ribeiro", "Martins", "Rocha", "Mendes", "Carvalho", "Nascimento", "Cavalcanti", "Barbosa", "Fernandes", "Sousa", "Melo", "Freitas", "Cardoso", "Santana", "Castro", "Andrade", "Araújo", "Azevedo", "Campos", "Duarte", "Figueiredo", "Gonçalves", "Lopes", "Marques", "Miranda", "Monteiro", "Morais", "Moreira", "Nunes", "Pinto", "Reis", "Sampaio", "Santos", "Teixeira", "Vieira", "Vargas", "Xavier", "Zimmermann", "Abreu", "Aguiar", "Albuquerque", "Alencar", "Alves", "Amaral", "Amorim", "Andrade", "Antunes", "Araújo", "Assis", "Azevedo", "Bastos", "Batista", "Bezerra", "Borges", "Braga", "Brito", "Cabral", "Caldeira", "Caldas", "Camacho", "Campos", "Cardoso", "Carneiro", "Carvalho", "Cavalcante", "Chaves", "Coelho", "Cordeiro", "Correa", "Cortês", "Coutinho", "Cruz", "Cunha", "Dias", "Domingues", "Duarte", "Elias", "Esteves", "Fagundes", "Farias", "Fernandes", "Ferraz", "Ferreira", "Figueiredo", "Flores", "Fontes", "Freitas", "Garcia", "Gaspar", "Gomes", "Gonçalves", "Guimarães", "Jesus", "Lima", "Lopes", "Luz", "Madeira", "Magalhães", "Marafigo", "Marinho", "Marques", "Martins", "Medeiros", "Melo", "Mendes", "Miranda", "Moraes", "Moreira", "Morais", "Nascimento", "Neves", "Nogueira", "Noronha", "Novais", "Oliveira", "Pacheco", "Paes", "Pais", "Peixoto", "Pereira", "Pinto", "Ramos", "Reis", "Ribeiro", "Rocha", "Rodrigues", "Sá", "Santana", "Santiago", "Santos", "Seabra", "Silva", "Simões", "Soares", "Sousa", "Souza", "Tavares", "Teixeira", "Torres", "Valente", "Vasconcelos", "Veiga", "Viana", "Vieira", "Vilela", "Xavier", "Zimmermann"];
    function gerarNome() {
      var nomeAleatorio = nomes[Math.floor(Math.random() * nomes.length)];
      var sobrenomeAleatorio = sobrenomes[Math.floor(Math.random() * sobrenomes.length)];
      var nomeCompleto = nomeAleatorio + " " + sobrenomeAleatorio;
      document.getElementById("nomeGerado").textContent = nomeCompleto;
    }